const BILI_PET_CONFIG = {
  SCHEMA_VERSION: 1,
  SOURCE: 'bili-pet-bridge',
  PET_BRIDGE_URL: 'http://127.0.0.1:39261/event',

  PROGRESS_INTERVAL_MS: 1000,
  SUBTITLE_SYNC_STEP_SEC: 0.5,
  BRIDGE_THROTTLE_MS: 1000,
  SUBTITLE_CONTEXT_BEFORE_SEC: 20,
  SUBTITLE_CONTEXT_AFTER_SEC: 8,

  ACTION_DEBOUNCE_MS: 400,

  DEFAULT_SETTINGS: {
    recordingEnabled: true,
    realtimePush: true,
  },
};

globalThis.BILI_PET_CONFIG = BILI_PET_CONFIG;
